### PR TITLE
Refactor align-items and align-self (#fails 377 -> 257)

### PR DESCRIPTION
**Pull request by pci**
Whilst dealing with some alignment issues I realised we're double up on some code: align-items does primary alignment then align-self does very similar alignment on an item by item basis. I suggest we use align-self as the main alignment code body and align-items just sets individual align-self properties if their undefined or 'auto'.

This involves a pretty big chunk of code being removed for align-items, so I thought I'd get your (@doctyper) opinion first, rather than pulling it straight into the main code base. The upshot is that the failed count goes down from about 380 to 260.

### CODE REVIEW

**Comment by doctyper** [comment]
Thanks. This is my current focus point at the moment. I'm dealing with some refactoring of align-content as a result, but should be stable enough to push my changes soon. 
(via thumbs)

**Comment by pci** [comment]
Ok, I had one look at align-content and got scared off!

Do you mind me pulling in these changes then?

**Comment by doctyper** [comment]
Actually, you should probably hold off. I'll merge these in manually.

**Comment by pci** [comment]
No problem, FYI I committed a few changes earlier that you might need to roll back if your doing a large refactor, and I'll hold off commiting for a while.

**Comment by doctyper** [comment]
Develop is updated. 255 failing tests.

**Pull request closed without merging**
