### PR TITLE
(Very) basis flex-grow support ( Issue 7 )

### PR DESCRIPTION
**Pull request by pci**
Does what it says in the title :)

I'll try to work on fleshing out this skeletal outline.

### CODE REVIEW

**Comment by doctyper** [comment]
@pci How's it coming with these? I just wrapped up the container properties so I can dive in here if I'm not toe-stepping.

**Comment by pci** [comment]
The more the merrier!

There are two main issues at the moment: Issue #25 (flex-basis processing) and the interaction between flex-grow/shrink and explicitly given height/weight, which is quite subtly.

Part of the problem is that I can't see a way within flexGrow.js to see if the height/width was given in the css, this causes problems especially with flex-shrink. Other than that the basics are there, it's just dotting all the i's and crossing all the t's.

**Comment by doctyper** [comment]
Do you mean if the width/height was declared in the style sheet vs. implied?

If so you can test the value of this.items[x].debug.auto.(width/height), where true = implied, false = declared.

**Comment by pci** [comment]
Thanks, that's good to know. I'm hoping to have some time in the next week to look at this, though feel free to look as well. I think I need to play around with flex-shrink in chrome to understand what's going on. However, flex-grow is nearly finished (although I've thought that before and been wrong!).

**Pull request merged**
