### PR TITLE
Order and `flex-direction: column` don't work together

### PR DESCRIPTION
**Pull request by pci**
I found that using order and flex-direction together sometimes came up with weird results. It took a long time to pin down but it was due to combinations of margin/padding/border compounding.

I ended up pulling some of the padding code from flex-wrap into flex-direction which then let me simplify the code somewhat. Also, I haven't managed to get the tests up and running my end (I can generate but not test), so I've only tested the attached code by hand, I've tried my best to be thorough in testing but I can't promise it doesn't introduce any new bugs!

### CODE REVIEW

**Comment by doctyper** [comment]
Huh. Bit confused since all flex-direction: column tests were passing as of the last stable check-in. I'm working on refactoring the test suite based on pairwise comparison. Hoping to get that in by this weekend.

**Comment by pci** [comment]
It was only on flex-direction: column (not even on column-reverse), the
children needed margin/padding/borders and it needed to wrap over at least
once - It might have been the test missed that combination. But looking
forward to the new test system!

**Comment by doctyper** [comment]
Merged into develop. I'm also giving you access to the repo.

The pairwise comparison took all available properties (save for some I'm on the fence about supporting) and generated a relevant testbed. The end result is about 1k generated tests, which is leaps better than the 750k original sample.

**Comment by pci** [comment]
Brilliant, thanks. Let me know when the new test system's up and running and I'll start bug hunting!

**Comment by doctyper** [comment]
It's up on develop. Same config as before, use /runner to run all tests.

**Comment by pci** [comment]
It's probably best the merge failed - it increase the number of failed tests! I'll close this pull and work through some of the tests to figure things out.

**Pull request closed without merging**
